# Generated by Django 3.2.5 on 2021-08-26 15:23

from django.db import migrations, models
import django.db.models.deletion
import grocery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Grocery List', max_length=80)),
                ('code', models.CharField(default=grocery.models.generate_unique_code, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quantity', models.FloatField(default=1)),
                ('units', models.CharField(default='', max_length=30)),
                ('details', models.CharField(max_length=80)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.groceries')),
            ],
        ),
    ]
