# Generated by Django 3.2.5 on 2021-07-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceries',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='title',
            field=models.CharField(default='Our Grocery List', max_length=80),
        ),
    ]
