# Generated by Django 3.2.5 on 2021-08-05 01:01

from django.db import migrations, models
import grocery.models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_alter_item_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceries',
            name='code',
            field=models.CharField(default=grocery.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
