# Generated by Django 3.2.5 on 2021-08-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
